import { Car, Car2, Car3, Car4 } from "../assets/images";

const data = [
  {
    name: "Koenigsegg",
    category: "Sport",
    image: Car,
    gas: "90L",
    type: "Manual",
    person: "2",
    price: "99",
    currency: "$",
  },
  {
    name: "Nissan GT - R",
    category: "Sport",
    image: Car2,
    gas: "85L",
    type: "Automatic",
    person: "2",
    price: "150",
    currency: "$",
  },
  {
    name: "Rolls - Royce",
    category: "Sedan",
    image: Car3,
    gas: "70L",
    type: "Manual",
    person: "2",
    price: "120",
    currency: "$",
  },
  {
    name: "Nissan GT - R",
    category: "Sport",
    image: Car4,
    gas: "75L",
    type: "Automatic",
    person: "2",
    price: "140",
    currency: "$",
  },
  {
    name: "McLaren",
    category: "Sport",
    image: Car,
    gas: "80L",
    type: "Manual",
    person: "2",
    price: "160",
    currency: "$",
  },
  {
    name: "Aston Martin",
    category: "Sport",
    image: Car,
    gas: "65L",
    type: "Automatic",
    person: "2",
    price: "170",
    currency: "$",
  },
  {
    name: "Bentley",
    category: "Luxury",
    image: Car2,
    gas: "95L",
    type: "Automatic",
    person: "4",
    price: "200",
    currency: "$",
  },
  {
    name: "Rolls Royce",
    category: "Luxury",
    image: Car4,
    gas: "100L",
    type: "Automatic",
    person: "4",
    price: "250",
    currency: "$",
  },
  {
    name: "Jaguar",
    category: "Luxury",
    image: Car3,
    gas: "85L",
    type: "Manual",
    person: "4",
    price: "130",
    currency: "$",
  },
  {
    name: "Tesla",
    category: "Electric",
    image: Car2,
    gas: "N/A",
    type: "Automatic",
    person: "4",
    price: "90",
    currency: "$",
  },
  {
    name: "Nissan Leaf",
    category: "Electric",
    image: Car,
    gas: "N/A",
    type: "Automatic",
    person: "4",
    price: "35",
    currency: "$",
  },
];

export default data;
